[GLOBAL]
pants_version = "2.31.0"

backend_packages = [
  "pants.backend.build_files.fmt.ruff",
  "pants.backend.python",
  "pants.backend.experimental.python.lint.ruff.check",
  "pants.backend.experimental.python.lint.ruff.format",
  "pants.backend.python.typecheck.mypy",
]

[source]
root_patterns = [
  "monorepo",
  "tests",
]

[python]
interpreter_constraints = ["CPython>=3.13,<4"]
enable_resolves = true
default_resolve = "default"

[python.resolves]
default = "third_party/python/default.lock"

